# Preview all emails at http://localhost:3000/rails/mailers/user_mailer
class UserMailerPreview < ActionMailer::Preview
  def contact_form
    UserMailer.contact_form("john@example.com", "John", "Tote bag blog echo park chicharrones flexitarian, yuccie kombucha authentic flannel artisan locavore. Leggings blue bottle vinyl, direct trade keffiyeh street art before they sold out craft beer typewriter roof party sriracha put a bird on it offal 3 wolf moon butcher. Fashion axe four loko waistcoat, sriracha forage affogato mixtape PBR&B mustache. Cronut 90's keytar bicycle rights tacos offal direct trade. Craft beer neutra green juice whatever tote bag authentic next level brooklyn seitan lomo. Brunch mustache roof party asymmetrical XOXO. Ennui PBR&B occupy pop-up, retro poutine photo booth roof party pitchfork fashion axe.

Pitchfork wolf kickstarter intelligentsia. Tote bag man braid freegan, ramps gluten-free offal cronut church-key intelligentsia dreamcatcher marfa sustainable chartreuse waistcoat meditation. 3 wolf moon cardigan pour-over, tousled hoodie semiotics PBR&B chartreuse. Brunch cold-pressed flannel YOLO, cliche gluten-free scenester etsy meggings direct trade cronut. Deep v waistcoat ugh 8-bit fanny pack pabst affogato gluten-free irony, kinfolk poutine. Austin schlitz fingerstache, cliche art party migas kale chips brunch banjo synth you probably haven't heard of them DIY waistcoat disrupt. Etsy paleo organic forage, typewriter vinyl ramps keffiyeh echo park fashion axe.

Kale chips narwhal affogato 8-bit small batch chambray. Locavore distillery bushwick ennui butcher organic. +1 yr narwhal selfies, tousled craft beer thundercats wayfarers. Schlitz green juice kinfolk, affogato +1 sustainable single-origin coffee gluten-free. Normcore banjo whatever cardigan, cliche tousled yr synth. Truffaut gastropub organic lo-fi freegan you probably haven't heard of them trust fund, umami cliche banjo authentic irony franzen. Chia meggings crucifix, wolf VHS pork belly synth.

Helvetica biodiesel squid normcore semiotics, vice bespoke polaroid YOLO neutra. Twee distillery intelligentsia fap microdosing. Typewriter etsy everyday carry, beard raw denim tote bag lumbersexual slow-carb meh mlkshk. Kickstarter brooklyn master cleanse, raw denim 3 wolf moon tilde leggings farm-to-table godard semiotics meggings salvia meditation actually. Keytar semiotics williamsburg pabst master cleanse. Cray normcore tofu, slow-carb raw denim letterpress banjo 8-bit polaroid distillery dreamcatcher next level fingerstache fap. Man braid sustainable blog craft beer biodiesel kitsch.")
  end
end