development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://pevmzusaxjsxdj:ERo_MzEshpsxQLvSY6y1j_Dq7H@ec2-54-225-64-254.compute-1.amazonaws.com:5432/ds0e3lq76qhho
